CoreDemo/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using CoreDemo.Models;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Linq;

namespace CoreDemo.Controllers
{
   
    public class WriterController : Controller
    {

        WriterManager vm = new WriterManager(new EfWriterRepository());
        Context c = new Context();

        [Authorize]
        public IActionResult Index()
        {
         
            return View();
        }
        public IActionResult WriterProfile()
        {
            return View();
        }
        public IActionResult Test()
        {
            return View();
        }
        public PartialViewResult WriterNavbarPartial()
        {
         
            return PartialView();
        }
        public PartialViewResult WriterFooterPartial()
        {
            return PartialView();
        }

        public PartialViewResult WriterHeaderPartial() 
        {
            return PartialView();
        }

        [HttpGet]
        public IActionResult WriterEditProfile() 
        {
            var userMail = User.Identity.Name;
            var writerId = c.Writers.Where(x => x.WriterMail == userMail).Select(y => y.WriterId).FirstOrDefault();
            var writerValues = vm.GetById(writerId);
            return View(writerValues);
        }

        [HttpPost]
        public IActionResult WriterEditProfile(Writer writer)
        {

            WriterValidator validator = new WriterValidator();  
            ValidationResult result = validator.Validate(writer);
            if (result.IsValid)
            {
                vm.Update(writer);
                return RedirectToAction("Index", "Dashboard");
            }
            else 
            {
                foreach(var item in result.Errors) 
                {
                    ModelState.AddModelError(item.PropertyName,item.ErrorMessage);
                }
            }
            return View();
          
        }

        [HttpGet]
        public IActionResult WriterAdd()
        {
            return View();
        }

        public IActionResult WriterAdd(AddProfileImage p)
        {
            Writer w = new Writer();
            if (p.WriterImage != null) 
            {
                var extension = Path.GetExtension(p.WriterImage.FileName);
                var newImageName = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/WriterImageFiles/",newImageName);
                var stream = new FileStream(location,FileMode.Create);
                p.WriterImage.CopyTo(stream);
                w.WriterImage = newImageName;
            }
            w.WriterMail = p.WriterMail;
            w.WriterName = p.WriterName;
            w.WriterPassword = p.WriterPassword;
            w.WriterStatus = p.WriterStatus;
            w.WriterAbout = p.WriterAbout;
            vm.Add(w);
            return RedirectToAction("Index", "Dashboard");
        }



    }
}

CoreDemo/Views/Writer/Index.cshtml
@{
    Layout = null;
}

<h1>Yazar Paneli</h1>
<h1>@ViewBag.v</h1>
<h1>@ViewBag.v1</h1>

CoreDemo/Views/Writer/WriterAdd.cshtml
@model CoreDemo.Models.AddProfileImage
@{
    ViewData["Title"] = "WriterAdd";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<form class="form-group" method="post" enctype="multipart/form-data">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                @Html.HiddenFor(x => x.WriterId)

                <div class="form-group">
                    <label for="exampleInputName1">Name</label>
                    @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriterName, "", new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    <label for="exampleInputEmail3">Email address</label>
                    @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriterMail, "", new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    <label for="exampleInputPassword4">Password</label>
                    @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriterPassword, "", new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    <label>Görsel</label>
                    <input type="file" name="WriterImage" />
                </div>

                <div class="form-group">
                    <label for="exampleTextarea1">Yazar Hakkında</label>
                    @Html.TextAreaFor(x => x.WriterAbout, 10, 2, new { @class = "form-control" })

                </div>
                <button type="submit" class="btn btn-gradient-primary mr-2">Kaydet</button>
                <button class="btn btn-light">İptal</button>

            </div>
        </div>
    </div>
</form>

CoreDemo/Views/Writer/WriterEditProfile.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewData["Title"] = "WriterEditProfile";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
<h1 class="grid-margin">Bilgilerini Güncelle</h1>

@using (Html.BeginForm("WriterEditProfile", "Writer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                @Html.HiddenFor(x=>x.WriterId)
               
                    <div class="form-group">
                        <label for="exampleInputName1">Name</label>
                        @Html.TextBoxFor(x=>x.WriterName, new {@class = "form-control"})
                    @Html.ValidationMessageFor(x => x.WriterName,"", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Email address</label>
                        @Html.TextBoxFor(x=>x.WriterMail, new {@class= "form-control"})
                    @Html.ValidationMessageFor(x => x.WriterMail,"", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword4">Password</label>
                        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WriterPassword,"", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        <label>Görsel</label>
                        <input type="file" name="img[]" class="file-upload-default">
                        <div class="input-group col-xs-12">
                            <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
                            <span class="input-group-append">
                                <button class="file-upload-browse btn btn-gradient-primary" type="button">Resim Seç</button>
                            </span>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="exampleTextarea1">Yazar Hakkında</label>
                        @Html.TextAreaFor(x => x.WriterAbout,10,2, new { @class = "form-control" })

                    </div>
                    <button type="submit" class="btn btn-gradient-primary mr-2">Kaydet</button>
                    <button class="btn btn-light">İptal</button>
              
            </div>
        </div>
    </div>
}

CoreDemo/Views/Writer/WriterFooterPartial.cshtml
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates </a> from Bootstrapdash.com</span>
    </div>
</footer>

CoreDemo/Views/Writer/WriterHeaderPartial.cshtml
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="../../index.html"><img src="~/writer/assets/images/logo.svg" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="../../index.html"><img src="~/writer/assets/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
        </button>
       
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <div class="nav-profile-img">
                        <img src="~/writer/assets/images/faces/face1.jpg" alt="image">
                        <span class="availability-status online"></span>
                    </div>
                    <div class="nav-profile-text">
                        <p class="mb-1 text-black">Yazar Adı Soyadı</p>
                    </div>
                </a>
                <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-cached mr-2 text-success"></i> Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-logout mr-2 text-primary"></i> Signout
                    </a>
                </div>
            </li>
            <li class="nav-item d-none d-lg-block full-screen-link">
                <a class="nav-link">
                    <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <i class="mdi mdi-email-outline"></i>
                    <span class="count-symbol bg-warning"></span>
                </a>
                @await Component.InvokeAsync("WriterMessageNotification")
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="mdi mdi-bell-outline"></i>
                    <span class="count-symbol bg-danger"></span>
                </a>
               @await Component.InvokeAsync("WriterNotification")
            </li>
            <li class="nav-item nav-logout d-none d-lg-block">
                <a class="nav-link" href="#">
                    <i class="mdi mdi-power"></i>
                </a>
            </li>
            <li class="nav-item nav-settings d-none d-lg-block">
                <a class="nav-link" href="#">
                    <i class="mdi mdi-format-line-spacing"></i>
                </a>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

CoreDemo/Views/Writer/WriterNavbarPartial.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="~/writer/assets/images/faces/face1.jpg" alt="profile">
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">Yazar Adı Soyadı</span>
                    <span class="text-secondary text-small">Yazılım Geliştirici</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Dashboard/Index">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/icons/mdi.html">
                <span class="menu-title">Profilim</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogListByWriter">
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogAdd">
                <span class="menu-title">Yeni Blog</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Message/Inbox">
                <span class="menu-title">Mesajlar</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/Index">
                <span class="menu-title">Siteye git</span>
                <i class="mdi mdi-car menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterEditProfile">
                <span class="menu-title">Ayarlar</span>
                <i class="mdi mdi-settings menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/tables/basic-table.html">
                <span class="menu-title">Çıkış yap</span>
                <i class="mdi mdi-logout menu-icon"></i>
            </a>
        </li>
        
    </ul>
</nav>

CoreDemo/Views/Writer/WriterProfile.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>WriterProfile</title>
</head>
<body>
    <h1>Writer Profile</h1>
</body>
</html>